<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:client="http://xmlns.oracle.com/SOAApplication4/LockheedCorporation/LockheedCorporationBPELProcess"
	xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	name="LockheedCorporationBPELProcess"
	targetNamespace="http://xmlns.oracle.com/SOAApplication4/LockheedCorporation/LockheedCorporationBPELProcess">
	<wsdl:documentation>
		<abstractWSDL>
			http://slc08aom.us.oracle.com:8001/soa-infra/services/default/LockheedCorporation!1.0/WSDLs/LockheedCorporationBPELProcess.wsdl
		</abstractWSDL>
	</wsdl:documentation>
	<plnk:partnerLinkType name="LockheedCorporationBPELProcess">
		<plnk:role name="LockheedCorporationBPELProcessProvider"
			portType="client:LockheedCorporationBPELProcess" />
	</plnk:partnerLinkType>
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema">
			<import
				namespace="http://xmlns.oracle.com/SOAApplication4/LockheedCorporation/LockheedCorporationBPELProcess"
				schemaLocation="test.xsd" />
		</schema>
	</wsdl:types>
	<wsdl:message name="LockheedCorporationBPELProcessRequestMessage">
		<wsdl:part name="payload" element="client:process" />
	</wsdl:message>
	<wsdl:message name="LockheedCorporationBPELProcessResponseMessage">
		<wsdl:part name="payload" element="client:processResponse" />
	</wsdl:message>
	<wsdl:portType name="LockheedCorporationBPELProcess">
		<wsdl:operation name="process">
			<wsdl:input message="client:LockheedCorporationBPELProcessRequestMessage" />
			<wsdl:output message="client:LockheedCorporationBPELProcessResponseMessage" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="LockheedCorporationBPELProcessBinding"
		type="client:LockheedCorporationBPELProcess">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="process">
			<soap:operation style="document" soapAction="process" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="lockheedcorporationbpelprocess_client_ep">
		<wsdl:port name="LockheedCorporationBPELProcess_pt"
			binding="client:LockheedCorporationBPELProcessBinding">
			<soap:address
				location="http://slc08aom.us.oracle.com:8001/soa-infra/services/default/LockheedCorporation/lockheedcorporationbpelprocess_client_ep" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>